import { execFileSync } from 'node:child_process'
import { mkdtempSync, readFileSync, rmSync, writeFileSync } from 'node:fs'
import { tmpdir } from 'node:os'
import { dirname, join, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..') // packages/client
const SRC = resolve(ROOT, 'src/app/widget.css')
const OUT_TS = resolve(ROOT, 'src/app/widget-css.generated.ts')

const tmp = mkdtempSync(join(tmpdir(), 'cmnt-css-'))
const outCss = join(tmp, 'widget.compiled.css')

try {
  // @tailwindcss/cli exposes the `tailwindcss` binary.
  execFileSync('pnpm', ['exec', 'tailwindcss', '-i', SRC, '-o', outCss, '--minify'], {
    cwd: ROOT,
    stdio: 'inherit',
  })
  const css = readFileSync(outCss, 'utf8')
  const banner = '// AUTO-GENERATED by scripts/build-css.mjs — do not edit. Run `pnpm build:css`.\n'
  writeFileSync(OUT_TS, `${banner}export const widgetCss = ${JSON.stringify(css)}\n`)
  console.log(`[build-css] wrote ${OUT_TS} (${css.length} bytes of CSS)`)
} finally {
  rmSync(tmp, { recursive: true, force: true })
}
